cleanup:
  path: "/home/iqbal/Downloads"

NotifyEmail:
  sendgrid: true
  sendgridAPI: "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"
  fromEmail: iquzart@hotmail.com
  fromName: "Muhammed Iqbal"
  toEMail: iquzart@gmail.com
  toName: "Muhammed Iqbal"
  emailSubject: "Jump Server Disk Usage"

