cleanup:
  path: "/home/iqbal/Downloads"

NotifyEmail:
  sendgrid: true
  sendgridAPI: ""
  fromEmail: iquzart@hotmail.com
  fromName: "Muhammed Iqbal"
  toEMail: iquzart@gmail.com
  toName: "Muhammed Iqbal"
  emailSubject: "Jump Server Disk Usage"

